// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AlternativaDto
    {
        /// <summary>
        /// Initializes a new instance of the AlternativaDto class.
        /// </summary>
        public AlternativaDto() { }

        /// <summary>
        /// Initializes a new instance of the AlternativaDto class.
        /// </summary>
        public AlternativaDto(int id, string texto)
        {
            Id = id;
            Texto = texto;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "texto")]
        public string Texto { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Texto == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Texto");
            }
            if (this.Texto != null)
            {
                if (this.Texto.Length > 100)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Texto", 100);
                }
                if (this.Texto.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Texto", 0);
                }
            }
        }
    }
}
