// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ColetaDto
    {
        /// <summary>
        /// Initializes a new instance of the ColetaDto class.
        /// </summary>
        public ColetaDto() { }

        /// <summary>
        /// Initializes a new instance of the ColetaDto class.
        /// </summary>
        public ColetaDto(DateTime? data = default(DateTime?), double? latitude = default(double?), double? longitude = default(double?), IList<RespostaDto> respostas = default(IList<RespostaDto>))
        {
            Data = data;
            Latitude = latitude;
            Longitude = longitude;
            Respostas = respostas;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public DateTime? Data { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "respostas")]
        public IList<RespostaDto> Respostas { get; set; }

    }
}
