// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DetalhesRespostaDto
    {
        /// <summary>
        /// Initializes a new instance of the DetalhesRespostaDto class.
        /// </summary>
        public DetalhesRespostaDto() { }

        /// <summary>
        /// Initializes a new instance of the DetalhesRespostaDto class.
        /// </summary>
        public DetalhesRespostaDto(int? idColeta = default(int?), int? idPergunta = default(int?), int? idOpcaoResposta = default(int?), string valor = default(string), PerguntaDto pergunta = default(PerguntaDto), AlternativaDto alternativas = default(AlternativaDto))
        {
            IdColeta = idColeta;
            IdPergunta = idPergunta;
            IdOpcaoResposta = idOpcaoResposta;
            Valor = valor;
            Pergunta = pergunta;
            Alternativas = alternativas;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idColeta")]
        public int? IdColeta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idPergunta")]
        public int? IdPergunta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idOpcaoResposta")]
        public int? IdOpcaoResposta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "valor")]
        public string Valor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pergunta")]
        public PerguntaDto Pergunta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alternativas")]
        public AlternativaDto Alternativas { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Pergunta != null)
            {
                this.Pergunta.Validate();
            }
            if (this.Alternativas != null)
            {
                this.Alternativas.Validate();
            }
        }
    }
}
