// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PerguntaSelecionadaDto
    {
        /// <summary>
        /// Initializes a new instance of the PerguntaSelecionadaDto class.
        /// </summary>
        public PerguntaSelecionadaDto() { }

        /// <summary>
        /// Initializes a new instance of the PerguntaSelecionadaDto class.
        /// </summary>
        public PerguntaSelecionadaDto(int? idPergunta = default(int?), int? ordem = default(int?))
        {
            IdPergunta = idPergunta;
            Ordem = ordem;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idPergunta")]
        public int? IdPergunta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ordem")]
        public int? Ordem { get; set; }

    }
}
