// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class QuestionarioPerguntaDto
    {
        /// <summary>
        /// Initializes a new instance of the QuestionarioPerguntaDto class.
        /// </summary>
        public QuestionarioPerguntaDto() { }

        /// <summary>
        /// Initializes a new instance of the QuestionarioPerguntaDto class.
        /// </summary>
        public QuestionarioPerguntaDto(string descricao = default(string), IList<PerguntaSelecionadaDto> perguntas = default(IList<PerguntaSelecionadaDto>))
        {
            Descricao = descricao;
            Perguntas = perguntas;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "perguntas")]
        public IList<PerguntaSelecionadaDto> Perguntas { get; set; }

    }
}
