// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class QuestionarioDto
    {
        /// <summary>
        /// Initializes a new instance of the QuestionarioDto class.
        /// </summary>
        public QuestionarioDto() { }

        /// <summary>
        /// Initializes a new instance of the QuestionarioDto class.
        /// </summary>
        public QuestionarioDto(int id, string nome)
        {
            Id = id;
            Nome = nome;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Nome == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Nome");
            }
            if (this.Nome != null)
            {
                if (this.Nome.Length > 500)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Nome", 500);
                }
                if (this.Nome.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Nome", 0);
                }
            }
        }
    }
}
