// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RespostaDto
    {
        /// <summary>
        /// Initializes a new instance of the RespostaDto class.
        /// </summary>
        public RespostaDto() { }

        /// <summary>
        /// Initializes a new instance of the RespostaDto class.
        /// </summary>
        public RespostaDto(int? idPergunta = default(int?), int? idOpcaoResposta = default(int?), string valor = default(string))
        {
            IdPergunta = idPergunta;
            IdOpcaoResposta = idOpcaoResposta;
            Valor = valor;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idPergunta")]
        public int? IdPergunta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idOpcaoResposta")]
        public int? IdOpcaoResposta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "valor")]
        public string Valor { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Valor != null)
            {
                if (this.Valor.Length > 500)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Valor", 500);
                }
                if (this.Valor.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Valor", 0);
                }
            }
        }
    }
}
