// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TipoPerguntaDto
    {
        /// <summary>
        /// Initializes a new instance of the TipoPerguntaDto class.
        /// </summary>
        public TipoPerguntaDto() { }

        /// <summary>
        /// Initializes a new instance of the TipoPerguntaDto class.
        /// </summary>
        public TipoPerguntaDto(int id, string descricao)
        {
            Id = id;
            Descricao = descricao;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Descricao == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Descricao");
            }
            if (this.Descricao != null)
            {
                if (this.Descricao.Length > 500)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Descricao", 500);
                }
                if (this.Descricao.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Descricao", 0);
                }
            }
        }
    }
}
