// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TokenDto
    {
        /// <summary>
        /// Initializes a new instance of the TokenDto class.
        /// </summary>
        public TokenDto() { }

        /// <summary>
        /// Initializes a new instance of the TokenDto class.
        /// </summary>
        public TokenDto(string token = default(string))
        {
            Token = token;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

    }
}
