// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ColetaApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UsuarioDto
    {
        /// <summary>
        /// Initializes a new instance of the UsuarioDto class.
        /// </summary>
        public UsuarioDto() { }

        /// <summary>
        /// Initializes a new instance of the UsuarioDto class.
        /// </summary>
        public UsuarioDto(string descricao = default(string), int? id = default(int?), string login = default(string), string senha = default(string), bool? acessoAdministrador = default(bool?), string nome = default(string), string cpf = default(string), string email = default(string), string telefone = default(string))
        {
            Descricao = descricao;
            Id = id;
            Login = login;
            Senha = senha;
            AcessoAdministrador = acessoAdministrador;
            Nome = nome;
            Cpf = cpf;
            Email = email;
            Telefone = telefone;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "login")]
        public string Login { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "senha")]
        public string Senha { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "acessoAdministrador")]
        public bool? AcessoAdministrador { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nome")]
        public string Nome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cpf")]
        public string Cpf { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "telefone")]
        public string Telefone { get; set; }

    }
}
