#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppSaudeFamilia.Resource", IsApplication=true)]

namespace AppSaudeFamilia
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AppSaudeFamilia.Servico.Resource.String.ApplicationName = global::AppSaudeFamilia.Resource.String.ApplicationName;
			global::AppSaudeFamilia.Servico.Resource.String.Hello = global::AppSaudeFamilia.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int button = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int fundo = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primaryText = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Backgroundmodaltopo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cancelar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EfeitoPressionadoModalOpcaoDir = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Efeitopressionadomodalopcaoesq = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int EfeitoPressionadoModalOpcaoUnica = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int EfeitoPressionarMenu = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int interogacao = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Menu = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int plus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sair = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int setaDireita = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int setaEsquerda = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sync = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sync_Desabilitado = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080025
			public const int absoluteLayout1 = 2131230757;
			
			// aapt resource value: 0x7f080009
			public const int btControleTreino = 2131230729;
			
			// aapt resource value: 0x7f080026
			public const int btnAnterior = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int btnCancelarQuestionario = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int btnConcluirQuestionario = 2131230760;
			
			// aapt resource value: 0x7f08001b
			public const int btnDir = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int btnEsq = 2131230745;
			
			// aapt resource value: 0x7f080008
			public const int btnLogin = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int btnNovaColeta = 2131230730;
			
			// aapt resource value: 0x7f08001d
			public const int btnOK = 2131230749;
			
			// aapt resource value: 0x7f080016
			public const int btnOKModal1Opcao1Msg = 2131230742;
			
			// aapt resource value: 0x7f080027
			public const int btnProximo = 2131230759;
			
			// aapt resource value: 0x7f08000e
			public const int btnSair = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int btnSincronizarColeta = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int imageView1 = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int imgItemMenu = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080015
			public const int linearLayout2 = 2131230741;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout3 = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int linearSairSistema = 2131230738;
			
			// aapt resource value: 0x7f08002a
			public const int menuLateral = 2131230762;
			
			// aapt resource value: 0x7f080020
			public const int rbOpcao1 = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int rbOpcao2 = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int rbOpcao3 = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int rbOpcao4 = 2131230755;
			
			// aapt resource value: 0x7f08001f
			public const int rdOpcoes = 2131230751;
			
			// aapt resource value: 0x7f080011
			public const int rightListView = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int rightMenu = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int scrollMenu = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int scrollView1 = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int textView1 = 2131230731;
			
			// aapt resource value: 0x7f080018
			public const int txtInfo = 2131230744;
			
			// aapt resource value: 0x7f08001c
			public const int txtInfo2 = 2131230748;
			
			// aapt resource value: 0x7f080017
			public const int txtInfoTitulo = 2131230743;
			
			// aapt resource value: 0x7f080002
			public const int txtItemMenu = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int txtPassword = 2131230727;
			
			// aapt resource value: 0x7f08001e
			public const int txtPergunta = 2131230750;
			
			// aapt resource value: 0x7f080024
			public const int txtResposta = 2131230756;
			
			// aapt resource value: 0x7f08000d
			public const int txtSincronizar = 2131230733;
			
			// aapt resource value: 0x7f080014
			public const int txtTituloModal1Msg1Opcao = 2131230740;
			
			// aapt resource value: 0x7f080006
			public const int txtUsuario = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int view1 = 2131230723;
			
			// aapt resource value: 0x7f08001a
			public const int view2 = 2131230746;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdapterItensMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Modal1Msg1Opcao = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Modal2Opcoes1Msg = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ModalMensagem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Pergunta = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MenuL = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int AutenticacaoInvalidaMensagem = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int AutenticacaoInvalidaTitulo = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int ConexaoInternetMensagem = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int ConexaoInternetTitulo = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int LoadingMensagem = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int LoadingTitulo = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int btnNovaColeta = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int btnSincronizarColeta = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int NoActionBar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int modal_theme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
